@startuml
rectangle "夜ご飯" as 1
rectangle "みそ汁" as 2
usecase "だし汁を沸かす" as 3
usecase "わかめを入れる" as 4
usecase "沸騰したら火を止める" as 6
usecase "味噌を溶かす" as 7
usecase "完成" as 25
usecase "ネギを入れる" as 5
rectangle "生姜焼き" as 8
rectangle "豚肉" as 17
usecase "薄く焼き目が付くまで焼く" as 18
usecase "タレと絡めて炒める" as 19
rectangle "タレ" as 9
usecase "生姜ひとかけの3/4をおろす" as 10
usecase "残りの生姜を細切りにして入れる" as 11
usecase "混ぜる" as 16
usecase "醤油大さじ5" as 12
usecase "みりん大さじ3" as 13
usecase "酒大さじ1" as 14
usecase "砂糖大さじ1" as 15
rectangle "キャベツの千切り" as 20
usecase "キャベツを切って盛り付ける" as 21
rectangle "だし巻き卵" as 22
usecase "卵2個とつゆのだしを混ぜる" as 23
note left
つゆのだしは4,5滴でいいかも
end note
usecase "たまごを焼く" as 24

1 --> 2
2 --> 3
3 --> 4
4 --> 6
6 --> 7
7 --> 25
3 --> 5
5 --> 6
1 --> 8
8 --> 17
17 --> 18
18 --> 19
19 --> 25
8 --> 9
9 --> 10
10 --> 11
11 --> 18
10 --> 16
16 --> 19
9 --> 12
12 --> 16
9 --> 13
13 --> 16
9 --> 14
14 --> 16
9 --> 15
15 --> 16
1 --> 20
20 --> 21
21 --> 25
1 --> 22
22 --> 23
23 --> 24
24 --> 25

@enduml

graph TD
	classDef doneColor fill:#868787
	1("夜ご飯")
	2("みそ汁")
	3(["だし汁を沸かす"])
	4(["わかめを入れる"])
	6(["沸騰したら火を止める"])
	7(["味噌を溶かす"])
	25(["完成"])
	5(["ネギを入れる"])
	8("生姜焼き")
	17("豚肉")
	18(["薄く焼き目が付くまで焼く"])
	19(["タレと絡めて炒める"])
	9("タレ")
	10(["生姜ひとかけの3/4をおろす"])
	11(["残りの生姜を細切りにして入れる"])
	16(["混ぜる"])
	12(["醤油大さじ5"])
	13(["みりん大さじ3"])
	14(["酒大さじ1"])
	15(["砂糖大さじ1"])
	20("キャベツの千切り")
	21(["キャベツを切って盛り付ける"])
	22("だし巻き卵")
	23(["卵2個とつゆのだしを混ぜる"])
	24(["たまごを焼く"])

	1 --> 2
	2 --> 3
	3 --> 4
	4 --> 6
	6 --> 7
	7 --> 25
	3 --> 5
	5 --> 6
	1 --> 8
	8 --> 17
	17 --> 18
	18 --> 19
	19 --> 25
	8 --> 9
	9 --> 10
	10 --> 11
	11 --> 18
	10 --> 16
	16 --> 19
	9 --> 12
	12 --> 16
	9 --> 13
	13 --> 16
	9 --> 14
	14 --> 16
	9 --> 15
	15 --> 16
	1 --> 20
	20 --> 21
	21 --> 25
	1 --> 22
	22 --> 23
	23 --> 24
	24 --> 25



### 夜ご飯
### みそ汁
- [ ] だし汁を沸かす
- [ ] わかめを入れる
- [ ] ネギを入れる
- [ ] 沸騰したら火を止める
- [ ] 味噌を溶かす
### 生姜焼き
### タレ
- [ ] 生姜ひとかけの3/4をおろす
- [ ] 残りの生姜を細切りにして入れる
- [ ] 醤油大さじ5
- [ ] みりん大さじ3
- [ ] 酒大さじ1
- [ ] 砂糖大さじ1
- [ ] 混ぜる
### 豚肉
- [ ] 薄く焼き目が付くまで焼く
- [ ] タレと絡めて炒める
### キャベツの千切り
- [ ] キャベツを切って盛り付ける
### だし巻き卵
- [ ] 卵2個とつゆのだしを混ぜる
- [ ] たまごを焼く
- [ ] 完成

