@startuml
rectangle "夜ご飯" as 1
rectangle "みそ汁" as 2
usecase "だし汁を沸かす" as 3
usecase "わかめを入れる" as 4
usecase "沸騰したら火を止める" as 6
usecase "味噌を溶かす" as 7
usecase "完成" as 20
usecase "ネギを入れる" as 5
rectangle "生姜焼き" as 8
rectangle "豚肉" as 15
usecase "薄く焼き目が付くまで焼く" as 16
usecase "タレと絡めて炒める" as 17
rectangle "タレ" as 9
usecase "醤油大さじ5" as 10
usecase "混ぜる" as 14
usecase "みりん大さじ3" as 11
usecase "酒大さじ1" as 12
usecase "砂糖大さじ1" as 13
rectangle "キャベツの千切り" as 18
usecase "キャベツを切って盛り付ける" as 19

1 --> 2
2 --> 3
3 --> 4
4 --> 6
6 --> 7
7 --> 20
3 --> 5
5 --> 6
1 --> 8
8 --> 15
15 --> 16
16 --> 17
17 --> 20
8 --> 9
9 --> 10
10 --> 14
14 --> 17
9 --> 11
11 --> 14
9 --> 12
12 --> 14
9 --> 13
13 --> 14
1 --> 18
18 --> 19
19 --> 20

@enduml

### 夜ご飯
### みそ汁
- [ ] だし汁を沸かす
- [ ] わかめを入れる
- [ ] ネギを入れる
- [ ] 沸騰したら火を止める
- [ ] 味噌を溶かす
### 生姜焼き
### タレ
- [ ] 醤油大さじ5
- [ ] みりん大さじ3
- [ ] 酒大さじ1
- [ ] 砂糖大さじ1
- [ ] 混ぜる
### 豚肉
- [ ] 薄く焼き目が付くまで焼く
- [ ] タレと絡めて炒める
### キャベツの千切り
- [ ] キャベツを切って盛り付ける
- [ ] 完成

